# Generated by Django 4.2.6 on 2023-12-05 19:24

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория товаров',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductDefect',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='обновленно в: ')),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='удалено в: ')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Колличество')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив? ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Бракованные товары',
                'verbose_name_plural': 'historical Бракованные товары',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='ProductNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='обновленно в: ')),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='удалено в: ')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('identification_number', models.CharField(max_length=200, unique=True, verbose_name='ID')),
                ('unit', models.CharField(choices=[('item', 'шт'), ('kilogram', 'кг'), ('liter', 'литр')], default='item', max_length=8, verbose_name='Ед.измерения')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('sum', models.IntegerField(default=0, verbose_name='Сумма')),
                ('state', models.CharField(choices=[('normal', 'норма'), ('defect', 'брак')], default='normal', max_length=20, verbose_name='Состояние')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив? ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductNormal', to='product.category')),
                ('warehouse', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='normal_products', to='product.warehouse', verbose_name='Склад (нормальный товар)')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Склад-Норм-Товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='обновленно в: ')),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='удалено в: ')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Колличество')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив? ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defective_products', to='product.productnormal', verbose_name='Бракованный товар')),
                ('warehouse', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='defect_products', to='product.warehouse', verbose_name='Склад (бракованный товар)')),
            ],
            options={
                'verbose_name': 'Бракованные товары',
                'verbose_name_plural': 'Бракованные товары',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductNormal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='обновленно в: ')),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='удалено в: ')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('identification_number', models.CharField(db_index=True, max_length=200, verbose_name='ID')),
                ('unit', models.CharField(choices=[('item', 'шт'), ('kilogram', 'кг'), ('liter', 'литр')], default='item', max_length=8, verbose_name='Ед.измерения')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('sum', models.IntegerField(default=0, verbose_name='Сумма')),
                ('state', models.CharField(choices=[('normal', 'норма'), ('defect', 'брак')], default='normal', max_length=20, verbose_name='Состояние')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив? ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.category')),
            ],
            options={
                'verbose_name': 'historical Товар',
                'verbose_name_plural': 'historical Склад-Норм-Товаров',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
