# Generated by Django 4.2.6 on 2023-12-05 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductnormal',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproductnormal',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.warehouse', verbose_name='Склад (нормальный товар)'),
        ),
        migrations.AddField(
            model_name='historicalproductdefect',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproductdefect',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.productnormal', verbose_name='Бракованный товар'),
        ),
        migrations.AddField(
            model_name='historicalproductdefect',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, default='2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.warehouse', verbose_name='Склад (бракованный товар)'),
        ),
    ]
