# Generated by Django 4.2.6 on 2023-12-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Гость', 'Гость'), ('Директор', 'Директор'), ('Завсклад', 'Завсклад')], default='Гость', max_length=100, verbose_name='Роль'),
        ),
    ]
