# Generated by Django 4.2.6 on 2023-12-05 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number_invoice', models.CharField(max_length=128, verbose_name='Номер накладной продажи')),
                ('sale_date', models.DateField(auto_now_add=True, verbose_name='Дата создания накладной продажи')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrib_invoice', to='distributor.distributor', verbose_name='дистрибьютор')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='transaction.invoice', verbose_name='Накладная')),
                ('product', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='product.productnormal', verbose_name='Товар из накладной')),
            ],
            options={
                'verbose_name': 'Проданная позиция',
                'verbose_name_plural': 'Проданные позиции',
            },
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(auto_now_add=True, verbose_name='Дата создания накладной возврата')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrib_return_invoice', to='distributor.distributor', verbose_name='Дистрибьютор')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnInvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('state', models.CharField(choices=[('normal', 'норма'), ('defect', 'брак')], default='normal', max_length=20, verbose_name='Состояние')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.invoiceitems', verbose_name='Товар из накладной продажи')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_product', to='transaction.returninvoice', verbose_name='Накладная возврата')),
            ],
            options={
                'verbose_name': 'Возвращенная  позиция',
                'verbose_name_plural': 'Возвращенные позиции',
            },
        ),
    ]
