# Generated by Django 4.2.6 on 2023-12-05 19:24

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='обновленно в: ')),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='удалено в: ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/distributor_images/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('region', models.CharField(max_length=150, verbose_name='Регион')),
                ('inn', models.CharField(max_length=20, unique=True, verbose_name='ИНН')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес по прописке')),
                ('actual_place_of_residence', models.CharField(max_length=255, verbose_name='Фактическое место жительства')),
                ('passport_series_number', models.CharField(max_length=100, unique=True, verbose_name='Серия, номер паспорта')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('validity', models.DateField(verbose_name='Срок действия')),
                ('contact', models.CharField(max_length=100, verbose_name='Контактный номер')),
                ('contact2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Второй контактный номер')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В АРХИВ')),
            ],
            options={
                'verbose_name': 'Дистрибьютор',
                'verbose_name_plural': 'Дистрибьюторы',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDistributor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='обновленно в: ')),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='удалено в: ')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Фотография')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('region', models.CharField(max_length=150, verbose_name='Регион')),
                ('inn', models.CharField(db_index=True, max_length=20, verbose_name='ИНН')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес по прописке')),
                ('actual_place_of_residence', models.CharField(max_length=255, verbose_name='Фактическое место жительства')),
                ('passport_series_number', models.CharField(db_index=True, max_length=100, verbose_name='Серия, номер паспорта')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('validity', models.DateField(verbose_name='Срок действия')),
                ('contact', models.CharField(max_length=100, verbose_name='Контактный номер')),
                ('contact2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Второй контактный номер')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В АРХИВ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Дистрибьютор',
                'verbose_name_plural': 'historical Дистрибьюторы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
